[event.ready]
# name: Bot name
# id  : Bot ID
output = "Logged in as {name} (ID: {id})"


[command.create]
name = "create"
description = "Create an editable message"

[command.create.options]
role.name = "role"
role.description = "Role that can edit the message (leave blank for everyone)"


[modal.edit]
title = "Edit message"
[modal.edit.input]
label = "New Content"
placeholder = "Enter new content"

